name: Deploy to hosting

on:
  push:
    branches: [ main ]

jobs:
  ftp-deploy:
    name: Copy files via FTP
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repository
        uses: actions/checkout@v4

      - name: Upload to hosting via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: ./www/taro-druga.ru/
          exclude: |
            **/.git*
            **/.git*/**
            **/server/**
            **/*.md
            **/*.pdf
